{
 "title": "Number of Likes",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": " Listening Timeline",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  listened_at AS \"time\",\r\n  user_username AS \"user\",\r\n  song_title AS \"song\"\r\nFROM\r\n  listening_history\r\nORDER BY\r\n  listened_at DESC;"
    }
   ]
  },
  {
   "title": " Top 5 Most Played Songs",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  song_title,\r\n  COUNT(*) AS listen_count\r\nFROM\r\n  listening_history\r\nGROUP BY\r\n  song_title\r\nORDER BY\r\n  listen_count DESC\r\nLIMIT 5;\r\n"
    }
   ]
  },
  {
   "title": "Most Active Users (Likes Given)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  ls.user_id AS username,\r\n  COUNT(ls.song_id) AS like_count\r\nFROM\r\n  liked_songs ls\r\nGROUP BY\r\n  ls.user_id\r\nORDER BY\r\n  like_count DESC\r\nLIMIT 5;"
    }
   ]
  },
  {
   "title": "Top Liked Songs",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  s.title AS song_title,\r\n  COUNT(ls.song_id) AS like_count\r\nFROM\r\n  songs s\r\nLEFT JOIN liked_songs ls ON s.title = ls.song_id\r\nGROUP BY\r\n  s.title\r\nORDER BY\r\n  like_count DESC;\r\n"
    }
   ]
  },
  {
   "type": "welcome",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Dashboards",
   "type": "dashlist",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Latest from the blog",
   "type": "news",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {}
   ]
  }
 ]
}