version: "3.8"

services:
  frontend:
    image: ghcr.io/cheschesiulia/frontend:latest
    ports:
      - "3000:80"
    networks:
      - auth-net
      - streaming-net
      - playlist-net
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.role == worker

  portainer:
    image: portainer/portainer-ce:latest
    ports:
      - "9443:9443"
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - auth-net
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  grafana:
    image: grafana/grafana:9.5.2
    user: "472:472"
    ports:
      - "3001:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana-provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana-provisioning/datasources:/etc/grafana/provisioning/datasources
    networks:
      - playlist-net
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager

  kong:
    image: kong:latest
    environment:
      - KONG_DATABASE=off
      - KONG_DECLARATIVE_CONFIG=/usr/local/kong/declarative/kong.yml
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
    ports:
      - "8000:8000"
      - "8001:8001"
    networks:
      - auth-net
      - streaming-net
      - playlist-net
    volumes:
      - ./kong.yml:/usr/local/kong/declarative/kong.yml
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  auth-service:
    image: ghcr.io/cheschesiulia/auth-service:latest
    ports:
      - "8002:8000"
    depends_on:
      - auth-db
    environment:
      - POSTGRES_USER=iuliasiangh
      - POSTGRES_PASSWORD=parolanoastra
      - POSTGRES_DB=auth_db
      - POSTGRES_PORT=5432
      - DATABASE_URL=postgresql://iuliasiangh:parolanoastra@auth-db:5432/auth_db
      - SECRET_KEY=iuliasupersecretangh
      - ALGORITHM=HS256
    networks:
      - auth-net
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.role == worker

  auth-db:
    image: postgres:14
    environment:
      - POSTGRES_USER=iuliasiangh
      - POSTGRES_PASSWORD=parolanoastra
      - POSTGRES_DB=auth_db
      - POSTGRES_PORT=5432
    volumes:
      - auth-db-data:/var/lib/postgresql/data
    networks:
      - auth-net
    ports:
      - "5433:5432"
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    networks:
      - auth-net
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  streaming-service:
    image: ghcr.io/cheschesiulia/streaming-service:latest
    ports:
      - "8003:8000"
    environment:
      - MINIO_ENDPOINT=http://gemdekaise.go.ro:9007
      - MINIO_ACCESS_KEY=admin
      - MINIO_SECRET_KEY=admin123
      - MINIO_BUCKET=melodii
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - SECRET_KEY=iuliasupersecretangh
      - ALGORITHM=HS256
    networks:
      - streaming-net
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.role == worker

  playlist-service:
    image: ghcr.io/cheschesiulia/playlist-service:latest
    ports:
      - "8004:8000"
    depends_on:
      - playlist-db
    environment:
      - POSTGRES_USER=iuliasiangh
      - POSTGRES_PASSWORD=parolanoastra
      - POSTGRES_DB=playlist_db
      - POSTGRES_PORT=5432
      - SECRET_KEY=iuliasupersecretangh
      - ALGORITHM=HS256
      - ENVIRONMENT=test
    networks:
      - playlist-net
      - streaming-net
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.role == worker

  playlist-db:
    image: postgres:14
    environment:
      - POSTGRES_USER=iuliasiangh
      - POSTGRES_PASSWORD=parolanoastra
      - POSTGRES_DB=playlist_db
      - POSTGRES_PORT=5432
    volumes:
      - playlist-db-data:/var/lib/postgresql/data
    networks:
      - playlist-net
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U iuliasiangh -d playlist_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure

volumes:
  auth-db-data:
  playlist-db-data:
  portainer_data:
  grafana_data:

networks:
  auth-net:
  streaming-net:
  playlist-net:
